#This creates a mesh, plots it and saves it
<prog> ::=<import> <params> <panels> <buildMesh> <glue> <save>
<import> ::= load "msh3" load "tetgen" load "medit"
<params> ::= real height=5,widthA=<n>,widthB=<n>;
<panels> ::= mesh panel1 = square(<n>,<n>,[height*x,widthA*y],flags=<flag>);mesh panel2 = square(<n>,<n>,[height*x,widthB*y]);
<buildMesh> ::= func ZZ1min = 0;func ZZ1max = widthB;func XX1 = x;func YY1 = y;mesh3 roofMesh = movemesh23(panel1,transfo=[XX1,YY1,ZZ1min],orientation=1);mesh3 fixedMesh = movemesh23(panel1,transfo=[XX1,YY1,ZZ1max],orientation=1);func ZZ2 = y;func XX2 = x;func YY2min = 0.;func YY2max = widthA;mesh3 lhsMesh = movemesh23(panel2,transfo=[XX2,YY2max,ZZ2],orientation=1);mesh3 rhsMesh = movemesh23(panel2,transfo=[XX2,YY2min,ZZ2],orientation=1);
<glue> ::= mesh3 glueMesh = lhsMesh+rhsMesh+roofMesh+fixedMesh;
<show> ::= medit("glueMesh",glueMesh,wait=1); 
<save> ::= savemesh(glueMesh,"test.mesh");
<n> ::= 1|2|3|4|5
<flag> ::= 0|1|2|3|4|5
