#grammar for evolving the section and airfoil of the BWB aircraft
<wing> ::= <sect0>{::}<sect1>{::}<foil0>{::}<foil1>{::}
<section> ::= {'Span':<r>, 'TC':<r>, 'RC':<r>, 'Sweep':<r>}
<airfoil> ::= {'Camber':<r>, 'Thickness':<r>}
<sect0> ::= self.plane['section2'] = <section>
<sect1> ::= self.plane['section3'] = <section>
<foil0> ::= self.plane['foil2'] = <airfoil>
<foil1> ::= self.plane['foil3'] = <airfoil>

<r> ::= 0.<digit><digit><digit><digit><digit>

<digit> ::= 1|2|3|4|5|6|7|8|9|0
