(defun trythis ()(car '(a b c d)))
(defun tryarg (l) (car l))
(trythis)
(tryarg '(a b c d))
(defun readlist()(read))
(readlist)
(defun factorial (n)
          (let ((sum 1))
            (dotimes (x n)
              (setf sum (* sum (1+ x))))
            sum))
