`./devolver.py -f run1`
`./devolver.py -f run2`
`./devolver.py -f run3`
`./devolver.py -f run4`
`./devolver.py -f run5`
`./devolver.py -f run6`
`./devolver.py -f run7`
`./devolver.py -f run8`
`./devolver.py -f run9`
`./devolver.py -f run10`
`./devolver.py -f run11`
`./devolver.py -f run12`
`./devolver.py -f run13`
`./devolver.py -f run14`
`./devolver.py -f run15`
`./devolver.py -f run16`
`./devolver.py -f run17`
`./devolver.py -f run18`
`./devolver.py -f run19`
`./devolver.py -f run20`
`./devolver.py -f run21`
`./devolver.py -f run22`
`./devolver.py -f run23`
`./devolver.py -f run24`
`./devolver.py -f run25`
`./devolver.py -f run26`
`./devolver.py -f run27`
`./devolver.py -f run28`
`./devolver.py -f run29`
`./devolver.py -f run30`
